on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
      - uses: jdx/mise-action@v2
      - run: ./gen.sh
      - uses: actions/upload-pages-artifact@v1
        with: { path: '.' }
      - uses: actions/deploy-pages@v2
        id: deployment
